name: ChatConduit
version: '${project.version}'
main: me.xydesu.chatconduit.Main
api-version: '1.20'
author: xydesu
description: ChatConduit - Next Generation Paper Chat System with full Chest GUI Control
softdepend: [PlaceholderAPI, DiscordSRV, InteractiveChat]

commands:
  chatconduit:
    description: ChatConduit 主指令
    aliases: [cc]
  channel:
    description: 開啟頻道選擇選單或切換頻道
    aliases: [ch]
  playerchannel:
    description: 玩家自訂群組頻道管理指令
    aliases: [pc]
  mute:
    description: 禁言玩家發言
    permission: chatconduit.admin.mute
  unmute:
    description: 解除玩家禁言
    permission: chatconduit.admin.unmute
  mutelist:
    description: 查看受禁言玩家清單
    permission: chatconduit.admin.mutelist
  msg:
    description: 發送跨服/本地私訊給指定玩家
    aliases: [tell, w, pm, whisper]
  reply:
    description: 快速回覆最後一位與您私訊的玩家
    aliases: [r]
  chatcolor:
    description: 開啟玩家發言文字顏色選擇 GUI 選單或自訂發言顏色
    aliases: [ccolor, color]
    permission: chatconduit.chatcolor

permissions:
  chatconduit.chatcolor:
    description: 允許使用 /chatcolor 選擇發言文字顏色
    default: true
  chatconduit.admin.mute:
    description: 允許執行 /mute 指令
    default: op
  chatconduit.admin.unmute:
    description: 允許執行 /unmute 指令
    default: op
  chatconduit.admin.mutelist:
    description: 允許執行 /mutelist 指令
    default: op