name: ChatConduit
version: '${project.version}'
main: me.xydesu.chatconduit.Main
api-version: '1.20'
author: xydesu
description: ChatConduit - Next Generation Paper Chat System with full Chest GUI Control
softdepend: [PlaceholderAPI, DiscordSRV]

commands:
  chatconduit:
    description: ChatConduit 主指令
    aliases: [cc]
  channel:
    description: 開啟頻道選擇選單或切換頻道
    aliases: [ch]
  playerchannel:
    description: 玩家自訂群組頻道管理指令
    aliases: [pc]
  mute:
    description: 禁言玩家發言
    permission: chatconduit.admin.mute
  unmute:
    description: 解除玩家禁言
    permission: chatconduit.admin.unmute
  mutelist:
    description: 查看受禁言玩家清單
    permission: chatconduit.admin.mutelist
  msg:
    description: 發送跨服/本地私訊給指定玩家
    aliases: [tell, w, pm, whisper]
  reply:
    description: 快速回覆最後一位與您私訊的玩家
    aliases: [r]
  chatcolor:
    description: 開啟玩家發言文字顏色選擇 GUI 選單或自訂發言顏色
    aliases: [ccolor, color]
    permission: chatconduit.chatcolor
  friend:
    description: 開啟好友系統主選單或執行好友社交指令
    aliases: [f, friends]
    permission: chatconduit.friend

permissions:
  chatconduit.friend:
    description: 允許使用好友系統與相關社交指令
    default: true
  chatconduit.use:
    description: 允許使用基礎聊天與頻道選單功能
    default: op
  chatconduit.create:
    description: 允許建立自訂玩家群組頻道
    default: op
  chatconduit.chatcolor:
    description: 允許使用 /chatcolor 選擇基礎發言文字顏色
    default: op
  chatconduit.chatcolor.gradient:
    description: 允許解鎖與使用漸變限定聊天顏色 (Sunset, Cyberpunk, Ocean, Emerald)
    default: op
  chatconduit.chatcolor.vip:
    description: 允許解鎖與使用 VIP 尊爵限定聊天顏色 (Sakura, Royal Gold)
    default: op
  chatconduit.chatcolor.rainbow:
    description: 允許解鎖與使用七彩幻光彩虹聊天顏色 (Rainbow)
    default: op
  chatconduit.chatcolor.hex:
    description: 允許使用自訂 RGB Hex 顏色碼 (#RRGGBB)
    default: op
  chatconduit.chat.color:
    description: 允許在聊天對話中使用基礎 Legacy 顏色碼 (&0~&f)
    default: op
  chatconduit.chat.color.hex:
    description: 允許在聊天對話中使用 RGB Hex 顏色碼 (&#RRGGBB)
    default: op
  chatconduit.chat.format:
    description: 允許在聊天對話中使用所有文字特殊效果 (&l, &o, &n, &m, &k)
    default: op
  chatconduit.chat.format.bold:
    description: 允許在聊天對話中使用粗體效果 (&l)
    default: op
  chatconduit.chat.format.italic:
    description: 允許在聊天對話中使用斜體效果 (&o)
    default: op
  chatconduit.chat.format.underline:
    description: 允許在聊天對話中使用底線效果 (&n)
    default: op
  chatconduit.chat.format.strikethrough:
    description: 允許在聊天對話中使用刪除線效果 (&m)
    default: op
  chatconduit.chat.format.magic:
    description: 允許在聊天對話中使用亂碼/閃爍效果 (&k)
    default: op
  chatconduit.admin:
    description: 允許執行 /chatconduit 管理指令
    default: op
  chatconduit.admin.mute:
    description: 允許執行 /mute 指令
    default: op
  chatconduit.admin.unmute:
    description: 允許執行 /unmute 指令
    default: op
  chatconduit.admin.mutelist:
    description: 允許執行 /mutelist 指令
    default: op
  chatconduit.admin.bypasslimit:
    description: 允許繞過玩家自訂群組頻道建立數量上限
    default: op