name: ChatConduit
version: '${project.version}'
main: me.xydesu.chatconduit.Main
api-version: '1.20'
author: xydesu
description: ChatConduit - Next Generation Paper Chat System with full Chest GUI Control
softdepend: [PlaceholderAPI, DiscordSRV, InteractiveChat]

commands:
  chatconduit:
    description: ChatConduit 主指令
    aliases: [cc]
  channel:
    description: 開啟頻道選擇選單或切換頻道
    aliases: [ch]
  playerchannel:
    description: 玩家自訂群組頻道管理指令
    aliases: [pc]