name: ChatConduit
version: '1.0'
main: me.xydesu.chatconduit.Main
api-version: '1.20'
softdepend: [PlaceholderAPI]

commands:
  chatconduit:
    description: ChatConduit 主指令
    aliases: [cc, chat]
    permission: chatconduit.use
  channel:
    description: 切換發言頻道
    aliases: [ ch ]
  playerchannel:
    description: 玩家自訂頻道管理指令
    aliases: [ pc, pchannel ]